### ISSUE TITLE
Which ARM template should be selected in Lab 2 Exercise 1 Step 2 -> 3 ?

### ISSUE THREAD

**Issue by keijiinoue** [ArtisConsulting/customer-insights-azure-data-workshop#1]
Which ARM template should be selected in Lab 2 Exercise 1 Step 2 -> 3 ?
As there is no description, it cannot be contined.

**Comment by furmangg** [comment]
If you click the Deploy to Azure button in the GitHub page then it will deploy the ARM template in the AzureSetup folder of this repo

**Comment by keijiinoue** [comment]
Great! Thank you!
