### ISSUE TITLE
There is no "Deploy to Azure" button in Lab 2 Exercise 1 Step 2 -> 2

### ISSUE THREAD

**Issue by keijiinoue** [ArtisConsulting/customer-insights-azure-data-workshop#2]
In Lab 2 Exercise 1 Step 2 -> 2, there is no "Deploy to Azure" button in the resource group -> Access control (IAM) page.
https://github.com/ArtisConsulting/customer-insights-azure-data-workshop/blob/main/lab02.md#step-2-deploy-the-arm-template

Therefore, the lab cannoe be continued.

**Comment by furmangg** [comment]
Sorry that wasn’t clear. You click the Deploy To Azure button on the GitHub page you linked. Don’t look for that button in the Azure Portal. That button is just a shortcut way of starting an ARM template deployment. 

Let me know if that doesn’t answer your question.

**Comment by keijiinoue** [comment]
Great! Thank you!
