### ISSUE TITLE
External table 'CustomerInsightsExport' is not accessible because content of directory cannot be listed.

### ISSUE THREAD

**Issue by keijiinoue** [ArtisConsulting/customer-insights-azure-data-workshop#3]
While running a SELECT script in Lab 3 -> Exercise 1 -> Step 2 -> 3, the following error shows in Messages area after clicking “Run”:

```
Started executing query at Line 1
External table 'CustomerInsightsExport' is not accessible because content of directory cannot be listed.
Total execution time: 00:00:00.830
```

![image](https://user-images.githubusercontent.com/18180976/148510028-7eeab411-9582-4599-b9af-52f21db1bd43.png)

It seems that IAM was set correctly.

![image](https://user-images.githubusercontent.com/18180976/148510289-cee6f32c-7cb1-4102-bf8b-1aaf1efd7647.png)

And Export from CI was successfully finished in advance, of course.

![image](https://user-images.githubusercontent.com/18180976/148510534-6bd2103e-7449-4f64-9c68-ffd0c49ecd27.png)

Please help me to run the SELECT script successfully.

**Comment by furmangg** [comment]
Go back to [Lab 2 Step 3.3](https://github.com/ArtisConsulting/customer-insights-azure-data-workshop/blob/main/lab02.md#step-3-grant-permissions-to-the-team) and make sure you have Storage Blob Data Contributor permissions. If you don’t, add it and any other missing permissions and wait 15 minutes. 

Glad you are getting to work through this! Let us know if you hit other snags! And let us know if that solves it.

**Comment by keijiinoue** [comment]
Thanks Greg,
I didn't grant Storage Blob Data Contributor role to my account.
After I granted and waited 15 minutes, it worked fine.
Please close this issue.

Thank you.
